name = "spellingisfun"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Durable Objects binding for Pages
[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"
script_name = "spellingisfun"
